// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_test_attributes
bool rcpp_test_attributes();
RcppExport SEXP testDllRcpp_rcpp_test_attributes() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_test_attributes());
    return __result;
END_RCPP
}
