// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_test_attributes
bool rcpp_test_attributes();
RcppExport SEXP dllrcpp_rcpp_test_attributes() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    bool __result = rcpp_test_attributes();
    return Rcpp::wrap(__result);
END_RCPP
}
